///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class FutureResponseListWeather {
/*
{
  "id": 501,
  "main": "Rain",
  "description": "moderate rain",
  "icon": "10d"
} 
*/

  int? id;
  String? main;
  String? description;
  String? icon;

  FutureResponseListWeather({
    this.id,
    this.main,
    this.description,
    this.icon,
  });
  FutureResponseListWeather.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    main = json['main']?.toString();
    description = json['description']?.toString();
    icon = json['icon']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['main'] = main;
    data['description'] = description;
    data['icon'] = icon;
    return data;
  }
}

class FutureResponseListFeels_like {
/*
{
  "day": 18.37,
  "night": 9.4,
  "eve": 10.66,
  "morn": 8.66
} 
*/

  double? day;
  double? night;
  double? eve;
  double? morn;

  FutureResponseListFeels_like({
    this.day,
    this.night,
    this.eve,
    this.morn,
  });
  FutureResponseListFeels_like.fromJson(Map<String, dynamic> json) {
    day = json['day']?.toDouble();
    night = json['night']?.toDouble();
    eve = json['eve']?.toDouble();
    morn = json['morn']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['day'] = day;
    data['night'] = night;
    data['eve'] = eve;
    data['morn'] = morn;
    return data;
  }
}

class FutureResponseListTemp {
/*
{
  "day": 19.15,
  "min": 8.2,
  "max": 19.15,
  "night": 9.4,
  "eve": 11,
  "morn": 9.01
} 
*/

  double? day;
  double? min;
  double? max;
  double? night;
  int? eve;
  double? morn;

  FutureResponseListTemp({
    this.day,
    this.min,
    this.max,
    this.night,
    this.eve,
    this.morn,
  });
  FutureResponseListTemp.fromJson(Map<String, dynamic> json) {
    day = json['day']?.toDouble();
    min = json['min']?.toDouble();
    max = json['max']?.toDouble();
    night = json['night']?.toDouble();
    eve = json['eve']?.toInt();
    morn = json['morn']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['day'] = day;
    data['min'] = min;
    data['max'] = max;
    data['night'] = night;
    data['eve'] = eve;
    data['morn'] = morn;
    return data;
  }
}

class FutureResponseList {
/*
{
  "dt": 1663606800,
  "sunrise": 1663584383,
  "sunset": 1663628038,
  "temp": {
    "day": 19.15,
    "min": 8.2,
    "max": 19.15,
    "night": 9.4,
    "eve": 11,
    "morn": 9.01
  },
  "feels_like": {
    "day": 18.37,
    "night": 9.4,
    "eve": 10.66,
    "morn": 8.66
  },
  "pressure": 1010,
  "humidity": 48,
  "weather": [
    {
      "id": 501,
      "main": "Rain",
      "description": "moderate rain",
      "icon": "10d"
    }
  ],
  "speed": 2.43,
  "deg": 132,
  "clouds": 47,
  "rain": 13.62
} 
*/

  int? dt;
  int? sunrise;
  int? sunset;
  FutureResponseListTemp? temp;
  FutureResponseListFeels_like? feels_like;
  int? pressure;
  int? humidity;
  List<FutureResponseListWeather?>? weather;
  double? speed;
  int? deg;
  int? clouds;
  double? rain;

  FutureResponseList({
    this.dt,
    this.sunrise,
    this.sunset,
    this.temp,
    this.feels_like,
    this.pressure,
    this.humidity,
    this.weather,
    this.speed,
    this.deg,
    this.clouds,
    this.rain,
  });
  FutureResponseList.fromJson(Map<String, dynamic> json) {
    dt = json['dt']?.toInt();
    sunrise = json['sunrise']?.toInt();
    sunset = json['sunset']?.toInt();
    temp = (json['temp'] != null)
        ? FutureResponseListTemp.fromJson(json['temp'])
        : null;
    feels_like = (json['feels_like'] != null)
        ? FutureResponseListFeels_like.fromJson(json['feels_like'])
        : null;
    pressure = json['pressure']?.toInt();
    humidity = json['humidity']?.toInt();
    if (json['weather'] != null) {
      final v = json['weather'];
      final arr0 = <FutureResponseListWeather>[];
      v.forEach((v) {
        arr0.add(FutureResponseListWeather.fromJson(v));
      });
      weather = arr0;
    }
    speed = json['speed']?.toDouble();
    deg = json['deg']?.toInt();
    clouds = json['clouds']?.toInt();
    rain = json['rain']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['dt'] = dt;
    data['sunrise'] = sunrise;
    data['sunset'] = sunset;
    if (temp != null) {
      data['temp'] = temp!.toJson();
    }
    if (feels_like != null) {
      data['feels_like'] = feels_like!.toJson();
    }
    data['pressure'] = pressure;
    data['humidity'] = humidity;
    if (weather != null) {
      final v = weather;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['weather'] = arr0;
    }
    data['speed'] = speed;
    data['deg'] = deg;
    data['clouds'] = clouds;
    data['rain'] = rain;
    return data;
  }
}

class FutureResponseCityCoord {
/*
{
  "lon": -74.0817,
  "lat": 4.6097
} 
*/

  double? lon;
  double? lat;

  FutureResponseCityCoord({
    this.lon,
    this.lat,
  });
  FutureResponseCityCoord.fromJson(Map<String, dynamic> json) {
    lon = json['lon']?.toDouble();
    lat = json['lat']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lon'] = lon;
    data['lat'] = lat;
    return data;
  }
}

class FutureResponseCity {
/*
{
  "id": 3688689,
  "name": "Bogota",
  "coord": {
    "lon": -74.0817,
    "lat": 4.6097
  },
  "country": "CO",
  "population": 1000000,
  "timezone": -18000
} 
*/

  int? id;
  String? name;
  FutureResponseCityCoord? coord;
  String? country;
  int? population;
  int? timezone;

  FutureResponseCity({
    this.id,
    this.name,
    this.coord,
    this.country,
    this.population,
    this.timezone,
  });
  FutureResponseCity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    coord = (json['coord'] != null)
        ? FutureResponseCityCoord.fromJson(json['coord'])
        : null;
    country = json['country']?.toString();
    population = json['population']?.toInt();
    timezone = json['timezone']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    if (coord != null) {
      data['coord'] = coord!.toJson();
    }
    data['country'] = country;
    data['population'] = population;
    data['timezone'] = timezone;
    return data;
  }
}

class FutureResponse {
/*
{
  "city": {
    "id": 3688689,
    "name": "Bogota",
    "coord": {
      "lon": -74.0817,
      "lat": 4.6097
    },
    "country": "CO",
    "population": 1000000,
    "timezone": -18000
  },
  "code": "200",
  "message": 19.924682,
  "cnt": 30,
  "list": [
    {
      "dt": 1663606800,
      "sunrise": 1663584383,
      "sunset": 1663628038,
      "temp": {
        "day": 19.15,
        "min": 8.2,
        "max": 19.15,
        "night": 9.4,
        "eve": 11,
        "morn": 9.01
      },
      "feels_like": {
        "day": 18.37,
        "night": 9.4,
        "eve": 10.66,
        "morn": 8.66
      },
      "pressure": 1010,
      "humidity": 48,
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "speed": 2.43,
      "deg": 132,
      "clouds": 47,
      "rain": 13.62
    }
  ]
} 
*/

  FutureResponseCity? city;
  String? code;
  double? message;
  int? cnt;
  List<FutureResponseList?>? list;

  FutureResponse({
    this.city,
    this.code,
    this.message,
    this.cnt,
    this.list,
  });
  FutureResponse.fromJson(Map<String, dynamic> json) {
    city = (json['city'] != null)
        ? FutureResponseCity.fromJson(json['city'])
        : null;
    code = json['code']?.toString();
    message = json['message']?.toDouble();
    cnt = json['cnt']?.toInt();
    if (json['list'] != null) {
      final v = json['list'];
      final arr0 = <FutureResponseList>[];
      v.forEach((v) {
        arr0.add(FutureResponseList.fromJson(v));
      });
      list = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (city != null) {
      data['city'] = city!.toJson();
    }
    data['code'] = code;
    data['message'] = message;
    data['cnt'] = cnt;
    if (list != null) {
      final v = list;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['list'] = arr0;
    }
    return data;
  }
}
